### PR TITLE
Fixes the button to open external link in new window on click

### LINKED ISSUE #2: external repo link target should be default browser
**The problem**
clicking on deepfence github buttons, renders github inside the docker desktop.

**Expectation**
Upon clicking any of the two buttons, open the GitHub url in the default browser.

image

### PR DESCRIPTION
**Pull request by pandyamarut**
Signed-off-by: pandyamarut <pandyamarut@gmail.com>

Fixes: https://github.com/deepfence/secretscanner-docker-extension/issues/2 

Summary: 

1. Uses internal method provided by Docker desktop client. 
2. Assigns functions to click event(onClick)

### CODE REVIEW

File: ui/src/Components/links.js [hunk 1]
```diff
@@ -3,25 +3,28 @@ import Chip from '@mui/material/Chip';
 import Stack from '@mui/material/Stack';
 import {GitHub} from '@mui/icons-material/';
 
-export default function Links() {
-    return (
-        <Stack direction="row" spacing={1} mt={1}>
-            <Chip icon={<GitHub />}
+export default function Links(props) {
+    let {ddClient} = props
```
Comment (ibreakthecloud) [inline ui/src/Components/links.js:7]: you need to pass ddClient from App.tsx to this component.
something like this
```js
<Links ddClient={ddClient}/>
```

**Review by ibreakthecloud — APPROVED** [review]
lgtm
